//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetCovoiturage.Resources.Models {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Trajet {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Trajet() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjetCovoiturage.Resources.Models.Trajet", typeof(Trajet).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Heure d&apos;arrivée.
        /// </summary>
        public static string HeurArrive {
            get {
                return ResourceManager.GetString("HeurArrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;heur d&apos;arrivée  est requis.
        /// </summary>
        public static string HeurArriveError {
            get {
                return ResourceManager.GetString("HeurArriveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Heure de départ.
        /// </summary>
        public static string HeurDepart {
            get {
                return ResourceManager.GetString("HeurDepart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;heure de depart  est requis.
        /// </summary>
        public static string HeurDepartError {
            get {
                return ResourceManager.GetString("HeurDepartError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Numéro de  trajet.
        /// </summary>
        public static string idTrajet {
            get {
                return ResourceManager.GetString("idTrajet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;id est requis.
        /// </summary>
        public static string idTrajetError {
            get {
                return ResourceManager.GetString("idTrajetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nombre de passagers.
        /// </summary>
        public static string NbPassagers {
            get {
                return ResourceManager.GetString("NbPassagers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le nombre de passegers  est requis.
        /// </summary>
        public static string NbPassagersError {
            get {
                return ResourceManager.GetString("NbPassagersError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nombre de places disponibles.
        /// </summary>
        public static string NbPlacesDisponible {
            get {
                return ResourceManager.GetString("NbPlacesDisponible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le nombre de places disponible   est requis.
        /// </summary>
        public static string NbPlacesDisponibleError {
            get {
                return ResourceManager.GetString("NbPlacesDisponibleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Point d&apos;arrivée.
        /// </summary>
        public static string PointArrive {
            get {
                return ResourceManager.GetString("PointArrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le point d&apos;arrivée  est requis.
        /// </summary>
        public static string PointArriveError {
            get {
                return ResourceManager.GetString("PointArriveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Point de départ.
        /// </summary>
        public static string PointDepart {
            get {
                return ResourceManager.GetString("PointDepart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le point de depart  est requis.
        /// </summary>
        public static string PointDepartError {
            get {
                return ResourceManager.GetString("PointDepartError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prix.
        /// </summary>
        public static string Prix {
            get {
                return ResourceManager.GetString("Prix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le prix   est requis.
        /// </summary>
        public static string PrixError {
            get {
                return ResourceManager.GetString("PrixError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ville de départ.
        /// </summary>
        public static string VilleDepart {
            get {
                return ResourceManager.GetString("VilleDepart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le ville  est requis.
        /// </summary>
        public static string VilleDepartError {
            get {
                return ResourceManager.GetString("VilleDepartError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ville de destination.
        /// </summary>
        public static string VilleDestination {
            get {
                return ResourceManager.GetString("VilleDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le ville  est requis.
        /// </summary>
        public static string VilleDestinationError {
            get {
                return ResourceManager.GetString("VilleDestinationError", resourceCulture);
            }
        }
    }
}
