//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetCovoiturage.Resources.Models {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TrajetHeureDate {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TrajetHeureDate() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjetCovoiturage.Resources.Models.TrajetHeureDate", typeof(TrajetHeureDate).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Arrival City.
        /// </summary>
        public static string ArrivalCity {
            get {
                return ResourceManager.GetString("ArrivalCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Arrival City is required.
        /// </summary>
        public static string ArrivalCityRequiredError {
            get {
                return ResourceManager.GetString("ArrivalCityRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Arrival Date.
        /// </summary>
        public static string ArrivalDate {
            get {
                return ResourceManager.GetString("ArrivalDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Arrival Date is required.
        /// </summary>
        public static string ArrivalDateRequiredError {
            get {
                return ResourceManager.GetString("ArrivalDateRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Arrival Hour.
        /// </summary>
        public static string ArrivalHour {
            get {
                return ResourceManager.GetString("ArrivalHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Arrival Hour is required.
        /// </summary>
        public static string ArrivalHourRequiredError {
            get {
                return ResourceManager.GetString("ArrivalHourRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Arrival Point.
        /// </summary>
        public static string ArrivalPoint {
            get {
                return ResourceManager.GetString("ArrivalPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Arrival Point is required.
        /// </summary>
        public static string ArrivalPointRequiredError {
            get {
                return ResourceManager.GetString("ArrivalPointRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Departure City.
        /// </summary>
        public static string DepartureCity {
            get {
                return ResourceManager.GetString("DepartureCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Departure City is required.
        /// </summary>
        public static string DepartureCityRequiredError {
            get {
                return ResourceManager.GetString("DepartureCityRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Departure Date.
        /// </summary>
        public static string DepartureDate {
            get {
                return ResourceManager.GetString("DepartureDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Departure Date is required.
        /// </summary>
        public static string DepartureDateRequiredError {
            get {
                return ResourceManager.GetString("DepartureDateRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Departure Hour.
        /// </summary>
        public static string DepartureHour {
            get {
                return ResourceManager.GetString("DepartureHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Departure Hour is required.
        /// </summary>
        public static string DepartureHourRequiredError {
            get {
                return ResourceManager.GetString("DepartureHourRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mileage.
        /// </summary>
        public static string Mileage {
            get {
                return ResourceManager.GetString("Mileage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mileage is required.
        /// </summary>
        public static string MileageRequiredError {
            get {
                return ResourceManager.GetString("MileageRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Number of seats left.
        /// </summary>
        public static string NumberSeatsLeft {
            get {
                return ResourceManager.GetString("NumberSeatsLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Number of seats left is required.
        /// </summary>
        public static string NumberSeatsLeftRequiredError {
            get {
                return ResourceManager.GetString("NumberSeatsLeftRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Price is required.
        /// </summary>
        public static string PriceRequiredError {
            get {
                return ResourceManager.GetString("PriceRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Starting Point.
        /// </summary>
        public static string StartingPoint {
            get {
                return ResourceManager.GetString("StartingPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Starting Point is required.
        /// </summary>
        public static string StartingPointRequiredError {
            get {
                return ResourceManager.GetString("StartingPointRequiredError", resourceCulture);
            }
        }
    }
}
